### ISSUE TITLE
Setup some kind of automated git push -> deploy process. Can this be done with travis-ci?

### ISSUE THREAD

**Issue by matthewtrask** [doctrine/doctrine-website-sculpin#1]
You could do a simple server on something like Laravel Forge and Travis where if Travis returns all tests passing, it will trigger Forge to deploy to production.

**Comment by jwage** [comment]
I think the whole thing could be done on Travis. The build and push to ghpages.

**Comment by matthewtrask** [comment]
yup, looks like here: https://docs.travis-ci.com/user/deployment/pages/

**Comment by jwage** [comment]
This is setup now 😁 Ended up going with a free tier AWS server that triggers a publish on push to master across this repo and any project repo that has docs.
